# Generated by Django 3.2.5 on 2022-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=512)),
                ('home_address', models.CharField(max_length=512)),
                ('route_length', models.DateTimeField()),
                ('morning_routine', models.DateTimeField()),
                ('classes_start', models.DateTimeField()),
                ('wake_up_time', models.DateTimeField()),
            ],
        ),
    ]
