# Generated by Django 3.2.5 on 2022-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wake_app_homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='classes_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='morning_routine',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_length',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='wake_up_time',
            field=models.TimeField(),
        ),
    ]
