# Generated by Django 3.2.5 on 2022-06-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wake_app_homework', '0002_auto_20220614_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('destination', 'home_address')},
        ),
    ]
